import ArticleCard from "@/app/[lang]/help/components/ArticleCard";
import getPosts from "@/services/blog/getPosts";
import getPostMetadata, {
    PostMetadata,
} from "@/services/website/getPostMetadata";
import { Post } from "@/types";
import { useParams } from "next/navigation";
import * as React from "react";

export interface IExploreOtherArticlesProps {
    currentPost: Post;
}

export default async function ExploreOtherArticles({
    currentPost,
}: IExploreOtherArticlesProps) {
    const posts = await getPosts();
    if (!posts) return;

    const recommendedPosts = posts
        ?.filter((post) => post?.id !== currentPost?.id)
        ?.slice(0, 4)
        ?.sort(() => Math.random() - 0.5); // for shuffling(maybe will not work since this page will be statically generated by nextjs for performance (SSG))

    if (!recommendedPosts?.length) return;

    return (
        <div className="space-y-3">
            <p className="text-xl font-semibold opacity-80">
                Explore Other Articles
            </p>
            <div className="grid gap-5 grid-cols-1 md:grid-cols-2">
                {recommendedPosts.map((post) => {
                    if (!post?.title || !post?.image) {
                        console.error("Failed to parse post ", post);
                        return "";
                    }
                    return (
                        <ArticleCard
                            key={post.title}
                            title={post.title}
                            slug={post.slug}
                            image={post.image}
                        />
                    );
                })}
            </div>
        </div>
    );
}
