import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import "./signup_styles.scss"
import "@/styles/globals.scss"
import "@/styles/globals.css"

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700', '800', '900'] })

export const metadata: Metadata = {
  title: 'NewsletterX - Signup',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
